### ISSUE TITLE
Remove short words from dictionary

### ISSUE THREAD

**Issue by yanns** [uschindler/german-decompounder#2]
Instead of using `"min_subword_size": 4`, I removed the short words from the dictionary:
```
sed -i. '/^..$/d; /^...$/d' <dict>
```
The dictionary is using less memory, and the index creation is faster in my experience.
What do think of that?

**Comment by uschindler** [comment]
I kept the short words, because I wanted to be flexible. But you are right, by removing them the dictionary gets small and you don't need the min_subword_size parameter.

**Comment by yanns** [comment]
thx for your opinion!
